<a href="https://colab.research.google.com/github/Laura-Burgmane/Python/blob/main/P%2306.07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PANDAS INTRO** (part 2) 06.07.2024.

In [1]:
import pandas as pd

In [2]:
data_list=[1,2,3,4,5] #this is list
print(data_list)

[1, 2, 3, 4, 5]

In [8]:
#creating dataframes:
dataframe_from_list = pd.DataFrame(data_list) #collection of series, have several columns; 2nd col fist 0 is col name
print(dataframe_from_list)

   0
0  1
1  2
2  3
3  4
4  5

**S E R I E S**

In [3]:
#CREATING PANDAS SERIES: only one column (first column is just an index (index always displayed in pandas), it is not a predefined col of data)
series_from_list = pd.Series(data_list)
print(series_from_list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
#SERIES FROM DATA FRAME:
data_dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50} #dictionary object key-value pairs
series_from_dict = pd.Series(data_dict)
print(series_from_dict)
#dtype:int64 - integer values

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [10]:
#SERIES FROM CSV LIST:
csv_data = "1,2,3,4,5"
csv_data.split(',')#first need to split the CSV file into a list:

['1', '2', '3', '4', '5']

In [12]:
series_from_list_split = pd.Series(csv_data.split(','))#creating series from CVS split list:
print(series_from_list_split)

0    1
1    2
2    3
3    4
4    5
dtype: object

**DATA_FRAMES**

In [18]:
#DATA FRAME: #this is a nested list
data_list = [
  ['John', 30, 68.5, True, 95.5],
  ['Alice', 25, 63.2, False, 88.0],
  ['Bob', 35, 71.0, True, 76.5],
  ['Eve', 28, 65.8, False, 92.0],
  ['Charlie', 40, 72.3, False, 87.5]
]
column_names = ['Name','Age','Weight','Is Student','Score']
pd.DataFrame(data_list, columns=column_names)

      Name  Age  Weight  Is Student  Score
0     John   30    68.5        True   95.5
1    Alice   25    63.2       False   88.0
2      Bob   35    71.0        True   76.5
3      Eve   28    65.8       False   92.0
4  Charlie   40    72.3       False   87.5

In [20]:
#Working with CSV file
df = pd.read_csv('/content/transaction_dataset.csv') #this is how a file is read-in

MOST COMMON METHODS IN DATA FRAMES:
* df.head()
* df.shape()
* df.sample()
* df.info()
* df.describe()
* df.describe(include = 'object')

In [21]:
df.head()#fist 5 rows of dataframe (5 is default)

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics

In [27]:
df.shape #how many rows and columns in the dataframe

(50000, 9)

In [26]:
df.sample(5) #to display 5(default) random samples

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
22652,328307,Robin,Erickson,F,26/10/1979,45.72,30/07/2023,Smith LLC,Restaurant
26993,239886,Louis,Sharp,M,01/11/1955,160.02,15/02/2023,Brooks LLC,Clothing
19858,347182,Alexis,Cook,F,30/10/1960,187.19,01/02/2023,Thomas-Odom,Cosmetic
12539,558196,Robert,Munoz,F,20/10/2003,12.41,17/02/2023,Neal PLC,Cosmetic
6922,260408,Tonya,Gentry,NaN,25/10/1981,149.30,04/10/2023,"Shaw, Page and Green",Clothing

In [25]:
df.info()#col names, data types (Dtype), how many values (NaN means not a number (either 0 or any number))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         50000 non-null  int64
 1   Name                50000 non-null  object
 2   Surname             50000 non-null  object
 3   Gender              44953 non-null  object
 4   Birthdate           50000 non-null  object
 5   Transaction Amount  50000 non-null  float64
 6   Date                50000 non-null  object
 7   Merchant Name       50000 non-null  object
 8   Category            50000 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 3.4+ MB

In [28]:
df.describe()#summary statistics of integers or floats

        Customer ID  Transaction Amount
count   50000.00000        50000.000000
mean   500136.79696          442.119239
std    288232.43164          631.669724
min        29.00000            5.010000
25%    251191.50000           79.007500
50%    499520.50000          182.195000
75%    749854.25000          470.515000
max    999997.00000         2999.880000

In [29]:
df.describe(include = 'object')#summary statistics including Strings

,Name,Surname,Gender,Birthdate,Date,Merchant Name,Category
count,50000,50000,44953,50000,50000,50000,50000
unique,690,1000,2,58,287,36939,6
top,Michael,Smith,F,01/11/1954,30/06/2023,Smith Ltd,Restaurant
freq,1167,1095,22713,914,200,69,8413

ACCESSING COLUMNS IN DATA FRAMES
* 3 WAYS TO ACCESS 1 PARTICULAR COLUMN:
* by name - df.['Gender'] #can access several columns
* by attribute - df.Gender
* by index  - df.iloc[:,;] #[row, column] / [:(means all rows), ;(means all columns)] / example [:, 3]

In [35]:
#ROBERTAS CODE FOR ACCESSING COL:
df['Gender'] # we access column by a name, we can access several columns

df.Gender # accessing column with an attribute

df.iloc[:, 3] # accessing column with index [row, column]

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [45]:
df['Gender']#access col by name

0        F
2        M
3        M
4        F
5        F
        ..
49995    F
49996    F
49997    M
49998    M
49999    F
Name: Gender, Length: 44953, dtype: object

In [46]:
#how many unique values?
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [47]:
df.Gender #by attribute; col name can not have spaces in the name; if there are spaces, need to use 'by name' method

0        F
2        M
3        M
4        F
5        F
        ..
49995    F
49996    F
49997    M
49998    M
49999    F
Name: Gender, Length: 44953, dtype: object

In [33]:
df.iloc[:, 3] #by index (: means all rows, 3 means 4. column counting from 0)

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [36]:
# VALUE COUNTS:
df['Gender'].value_counts()

Gender
F    22713
M    22240
Name: count, dtype: int64

In [37]:
# VALUE COUNTS without dropping empty values(non-number values):
df['Gender'].value_counts(dropna=False)

Gender
F      22713
M      22240
NaN     5047
Name: count, dtype: int64

In [38]:
#HOW MANY EMPTY VALUES: to check if all the values ARE empty (true or false)
df.isna()#binary False = 0, True = 1
#.sum() shows how many empty values in total are there in the column
df.isna().sum()

Customer ID              0
Name                     0
Surname                  0
Gender                5047
Birthdate                0
Transaction Amount       0
Date                     0
Merchant Name            0
Category                 0
dtype: int64

In [39]:
#REVERSE OF PREVIOUS: to check if all the values are NOT empty (true or false)
df.notna()
df.notna().all()

Customer ID            True
Name                   True
Surname                True
Gender                False
Birthdate              True
Transaction Amount     True
Date                   True
Merchant Name          True
Category               True
dtype: bool

In [40]:
#drop empty values:
df.dropna()#does not override the existing dataframe, its just an empty method
#to use the new filtered (without empty values) DF, need to:
#either save it in new DF: df_new_dataframe = df.dropna()
#or, with this method to ovveride the current df witht the new one:
#df.dropna(inplace=True)

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics
5,576539,Monica,Bartlett,F,20/10/2001,99.14,24/08/2023,"Tran, Torres and Joyce",Cosmetic
...,...,...,...,...,...,...,...,...,...
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [48]:
df.dropna(inplace=True) #cleans data from empty values, but does not display them, generates new data frame that can be saved

In [43]:
#to save cleaned data: (appears as another file to the left in folder tree to be used in for example excel)
df.to_csv('cleaned_data.csv')